name:  GitHub Actions Demo

on: push

jobs:
 build:
  runs-on: ubantu-latest

  steps:
   - name: Checkout repository
     uses: actions/checkout@v4

   - name: List files
     run: echo ls -ltr










